"""Regenerate tests/data/vlen_goldens.json from the Python oracle.

Run inside espg/zarr-vlen-ndarray's environment (the wire-format reference,
englacial/zagg spec section 1.4 / section 6.2):

    cd /path/to/zarr-vlen-ndarray && uv run python /path/to/moczarr-js/scripts/generate_vlen_fixtures.py

The cases mirror that package's tests: ``test_byte_identity.py::test_golden_framing``
(including the empty element) and ``conftest.py``'s ``float32_cells`` /
``uint64_cells`` (seeds 42 / 7). ``raw_hex`` is the numcodecs VLenBytes
framing; ``zstd3_hex`` the same chunk through zarr's ``ZstdCodec(level=3)``.
"""

from __future__ import annotations

import json
import pathlib
import struct
import sys
import tempfile

import numpy as np
import zarr
from zarr.codecs import ZstdCodec
from zarr_vlen_ndarray import NDArray, VlenNDArrayCodec

OUT = pathlib.Path(__file__).resolve().parent.parent / "tests" / "data" / "vlen_goldens.json"


def as_object_array(cells: list[np.ndarray]) -> np.ndarray:
    out = np.empty(len(cells), dtype=object)
    out[:] = cells
    return out


def frame(cells: list[np.ndarray]) -> bytes:
    """The section 1.4 framing, written out by hand (the independent oracle)."""
    buf = struct.pack("<I", len(cells))
    for cell in cells:
        payload = cell.tobytes()
        buf += struct.pack("<I", len(payload)) + payload
    return buf


def values(cell: np.ndarray) -> list:
    if cell.dtype == np.uint64:
        return [str(int(v)) for v in cell.ravel()]  # JSON numbers cannot carry uint64
    return [float(v) for v in cell.ravel()]  # float32 -> exact float64 repr


def case(cells: list[np.ndarray], zdtype: NDArray, element: dict) -> dict:
    out = {
        "element": element,
        "cells": [values(c) for c in cells],
        "shape_per_cell": [list(c.shape) for c in cells],
        "raw_hex": frame(cells).hex(),
    }
    with tempfile.TemporaryDirectory() as tmp:
        root = pathlib.Path(tmp)
        for compressors, tag in ((None, "raw"), (ZstdCodec(level=3), "zstd3")):
            arr = zarr.create_array(
                store=root / tag,
                shape=(len(cells),),
                chunks=(len(cells),),
                dtype=zdtype,
                serializer=VlenNDArrayCodec(),
                compressors=compressors,
            )
            arr[:] = as_object_array(cells)
            written = (root / tag / "c" / "0").read_bytes()
            if tag == "raw":
                assert written.hex() == out["raw_hex"], "hand framing must match the codec"
            out[f"{tag}_hex"] = written.hex()
    return out


def main() -> None:
    f32 = {"dtype": "float32", "shape": [None, 2]}
    u64 = {"dtype": "uint64", "shape": [None]}
    golden = [
        np.array([[1.0, 2.0], [3.0, 4.0]], dtype="<f4"),
        np.empty((0, 2), dtype="<f4"),
        np.array([[5.5, 6.5]], dtype="<f4"),
    ]
    rng = np.random.default_rng(42)
    float32_cells = [rng.random((n, 2)).astype("<f4") for n in (3, 0, 7, 1, 250, 0)]
    rng = np.random.default_rng(7)
    uint64_cells = [
        rng.integers(0, 2**63, size=n, dtype=np.uint64).astype("<u8") for n in (5, 0, 1, 12, 0, 3)
    ]
    cases = {
        "golden_framing": case(golden, NDArray(dtype="float32", shape=(None, 2)), f32),
        "float32_2col": case(float32_cells, NDArray(dtype="float32", shape=(None, 2)), f32),
        "uint64_flat": case(uint64_cells, NDArray(dtype="uint64", shape=(None,)), u64),
        # zarr elides an all-fill chunk from disk, so this one is framed by hand only.
        "all_empty": {
            "element": f32,
            "cells": [[], []],
            "shape_per_cell": [[0, 2], [0, 2]],
            "raw_hex": frame([np.empty((0, 2), "<f4")] * 2).hex(),
        },
    }
    doc = {
        "comment": (
            "Golden vlen-ndarray framing vectors ported from espg/zarr-vlen-ndarray tests "
            "(test_byte_identity.py::test_golden_framing + conftest float32_cells/uint64_cells, "
            "seeds 42/7): raw_hex is the numcodecs VLenBytes framing (u32le count, per cell "
            "u32le length + LE payload), zstd3_hex the same chunk through zarr's "
            "ZstdCodec(level=3), byte-identical to the vlen-bytes codec path. Generated by "
            "scripts/generate_vlen_fixtures.py."
        ),
        "versions": {"zarr": zarr.__version__, "numpy": np.__version__},
        "cases": cases,
    }
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(f"wrote {OUT}", file=sys.stderr)


if __name__ == "__main__":
    main()
