"""Regenerate tests/data/tdigest_goldens.json from the Python reference.

Run inside espg/moczarr's environment (the kernels under test are
``moczarr.tdigest.cdf_from_tdigest`` / ``quantile_from_tdigest`` and
``moczarr.hhdc.rasterize_cell`` / ``chunk_z_range``):

    cd /path/to/moczarr && uv run python /path/to/moczarr-js/scripts/generate_tdigest_fixtures.py

The digests are the populated cells of the vendored zagg section-7
conformance fixtures (tests/data/spec/*.expected.json) plus a few
hand-built edge cases (single centroid, tied means, all-equal means).
"""

from __future__ import annotations

import json
import math
import pathlib
import sys

import numpy as np

import moczarr
from moczarr.hhdc import chunk_z_range, rasterize_cell
from moczarr.tdigest import cdf_from_tdigest, quantile_from_tdigest

ROOT = pathlib.Path(__file__).resolve().parent.parent
SPEC = ROOT / "tests" / "data" / "spec"
OUT = ROOT / "tests" / "data" / "tdigest_goldens.json"

QUANTILES = [0.0, 0.05, 0.25, 0.5, 0.75, 0.95, 1.0]


def digest(rows: list[list[float]]) -> np.ndarray:
    return np.asarray(rows, dtype=np.float32).reshape(-1, 2)


def queries(d: np.ndarray) -> list[float]:
    """Edges spanning the digest, the centroid means themselves (tie points),
    and points outside both ends."""
    means = d[:, 0].astype(np.float64)
    lo, hi = math.floor(means.min()) - 1.0, math.ceil(means.max()) + 1.0
    edges = (lo + (hi - lo) * np.arange(33) / 32).tolist()
    return sorted(set(edges + means.tolist() + [lo - 5.0, hi + 5.0]))


def case(name: str, rows: list[list[float]]) -> dict:
    d = digest(rows)
    xs = queries(d)
    z_lo = float(math.floor(d[:, 0].min()))
    out = {
        "name": name,
        "digest": rows,
        "x": xs,
        "cdf": np.asarray(cdf_from_tdigest(d, np.asarray(xs)), dtype=np.float64).tolist(),
        "quantiles": {str(q): quantile_from_tdigest(d, q) for q in QUANTILES},
        "raster": {
            "z_lo": z_lo,
            "resolution": 0.5,
            "n_bins": 64,
            "counts": rasterize_cell(d, z_lo, 0.5, 64).tolist(),
        },
    }
    return out


def fixture_digests(name: str, field: str) -> list[tuple[str, list[list[float]]]]:
    exp = json.loads((SPEC / f"{name}.expected.json").read_text())
    return [(f"{name}:{field}:cell{c['index']}", c[field]) for c in exp["cells"] if c.get(field)]


def main() -> None:
    cases = []
    for name, field in (
        ("minimal", "h_tdigest"),
        ("kitchen_sink", "h_tdigest_signal"),
        ("kitchen_sink", "h_tdigest_noise"),
        ("flux", "rx_flux"),
    ):
        for label, rows in fixture_digests(name, field):
            cases.append(case(label, rows))
    cases.append(case("edge:single_centroid", [[31.301000595092773, 1.0]]))
    cases.append(case("edge:tied_means", [[10.0, 1.0], [10.0, 3.0], [12.0, 2.0]]))
    cases.append(case("edge:all_equal_means", [[7.5, 2.0], [7.5, 2.0], [7.5, 5.0]]))
    cases.append(case("edge:two_centroids", [[0.0, 4.0], [1.0, 4.0]]))

    # chunk-level window derivation over minimal/'s populated digests (the
    # read_tensors per-block step), under each fit policy.
    minimal = [digest(rows) for _, rows in fixture_digests("minimal", "h_tdigest")]
    windows = {}
    for fit in ("raise", "degrade_resolution", "collapse_bins"):
        for n_bins, resolution in ((64, 0.5), (16, 0.5), (128, 0.1)):
            key = f"{fit}:{n_bins}:{resolution}"
            try:
                z_lo, nb, res = chunk_z_range(
                    minimal, n_bins=n_bins, resolution=resolution, bottom=0.05, top=0.95, fit=fit
                )
                windows[key] = {"z_lo": z_lo, "n_bins": nb, "resolution": res}
            except ValueError as exc:
                windows[key] = {"error": str(exc).split(";")[0]}

    doc = {
        "comment": (
            "t-digest kernel goldens from the Python reference (moczarr.tdigest / moczarr.hhdc) "
            "over the vendored zagg section-7 fixture digests plus hand-built edge cases. "
            "Generated by scripts/generate_tdigest_fixtures.py."
        ),
        "versions": {"moczarr": moczarr.__version__, "numpy": np.__version__},
        "quantiles": QUANTILES,
        "cases": cases,
        "chunk_z_range": {"digests": "minimal:h_tdigest (all populated cells)", "windows": windows},
    }
    OUT.write_text(json.dumps(doc, indent=1) + "\n")
    print(f"wrote {OUT} ({len(cases)} cases)", file=sys.stderr)


if __name__ == "__main__":
    main()
